"""followers

Revision ID: 584ad6aa63d4
Revises: ac68d2fa3cb1
Create Date: 2021-04-19 15:00:34.068231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584ad6aa63d4'
down_revision = 'ac68d2fa3cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
